CREATE TABLE users(
	id BIGSERIAL PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	name VARCHAR(120) NOT NULL,
	lastname VARCHAR(120) NOT NULL,
	phone VARCHAR(120) NOT NULL UNIQUE,
	image VARCHAR(125) NULL,
	password VARCHAR(125) NOT NULL,
	is_available BOOLEAN NULL,
	session_token VARCHAR(255) NULL,
	create_at TIMESTAMP(0) NOT NULL,
	update_at TIMESTAMP(0) NOT NULL
	
);